branch-defaults:
  master:
    environment: banzee-dev-env
environment-defaults:
  banzee-dev-env:
    branch: null
    repository: null
global:
  application_name: banzee-dev
  default_ec2_keyname: vincle-keypair-uw2-dev
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/Python 3.6 running on 64bit Amazon Linux/2.6.0
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
